In [34]:
import pandas as pd

# Where are duplicate umi counts coming from?

In [7]:
puro_no_err_corr_trebl_exp = pd.read_csv("/global/scratch/projects/fc_mvslab/OpenProjects/Sanjana/TREBL/output/NKX2-2/TL4B2/puro_only/no_err_corr/AD_activities.csv",
                                        header = [0,1], index_col = [0,1])
puro_no_err_corr_trebl_exp

timepoint                                                            0  \
metric                                                 bc_activity_avg
AD                                                 rep
ACCGACGCCATCGACGAGGAGGTGGCCATGAGCGCCGTGATCGAGAT... 1               NaN
                                                   2               inf
                                                   3               NaN
                                                   4               NaN
ACCGACTTCATCGACGAGGAGGTGATCATGAGCATCGTGATCGAGAT... 1          6.513889
...                                                                ...
TTCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCAG... 4               inf
TTCGCCGACGCCACCCAGGCCGCCCTGCAGGCCGGCATTCCCTTCAG... 1               inf
                                                   2               inf
                                                   3               inf
                                                   4               inf

timepoint                                                               \
metric                                                 bc_activity_std
AD                                                 rep
ACCGACGCCATCGACGAGGAGGTGGCCATGAGCGCCGTGATCGAGAT... 1               NaN
                                                   2               NaN
                                                   3               NaN
                                                   4               NaN
ACCGACTTCATCGACGAGGAGGTGATCATGAGCATCGTGATCGAGAT... 1          9.172746
...                                                                ...
TTCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCAG... 4               NaN
TTCGCCGACGCCACCCAGGCCGCCCTGCAGGCCGGCATTCCCTTCAG... 1               NaN
                                                   2               NaN
                                                   3               NaN
                                                   4               NaN

timepoint                                                               \
metric                                                 pooled_activity
AD                                                 rep
ACCGACGCCATCGACGAGGAGGTGGCCATGAGCGCCGTGATCGAGAT... 1               NaN
                                                   2               inf
                                                   3               NaN
                                                   4               NaN
ACCGACTTCATCGACGAGGAGGTGATCATGAGCATCGTGATCGAGAT... 1          0.205479
...                                                                ...
TTCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCAG... 4          1.468085
TTCGCCGACGCCACCCAGGCCGCCCTGCAGGCCGGCATTCCCTTCAG... 1          9.200000
                                                   2          0.250229
                                                   3          4.128205
                                                   4          1.477612

timepoint                                                            4  \
metric                                                 bc_activity_avg
AD                                                 rep
ACCGACGCCATCGACGAGGAGGTGGCCATGAGCGCCGTGATCGAGAT... 1               NaN
                                                   2          0.215686
                                                   3          0.807692
                                                   4          1.363636
ACCGACTTCATCGACGAGGAGGTGATCATGAGCATCGTGATCGAGAT... 1          0.209914
...                                                                ...
TTCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCAG... 4               inf
TTCGCCGACGCCACCCAGGCCGCCCTGCAGGCCGGCATTCCCTTCAG... 1               inf
                                                   2               inf
                                                   3               inf
                                                   4               inf

timepoint                                                               \
metric                                                 bc_activity_std
AD                                                 rep
ACCGACGCCATCGACGAGGAGGTGGCCATGAGCGCCGTGATCGAGAT... 1               NaN
                                                   2               NaN
                                                   3               NaN
                                                   4               NaN
ACCGACTTCATCGACGAGGAGGTGATCATGAGCATCGTGATCGAGAT... 1          0.275436
...                                                                ...
TTCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCAG... 4               NaN
TTCGCCGACGCCACCCAGGCCGCCCTGCAGGCCGGCATTCCCTTCAG... 1               NaN
                                                   2               NaN
                                                   3               NaN
                                                   4               NaN

timepoint                                                               \
metric                                                 pooled_activity
AD                                                 rep
ACCGACGCCATCGACGAGGAGGTGGCCATGAGCGCCGTGATCGAGAT... 1               NaN
                                                   2          0.215686
                                                   3          0.807692
                                                   4          1.363636
ACCGACTTCATCGACGAGGAGGTGATCATGAGCATCGTGATCGAGAT... 1          0.363344
...                                                                ...
TTCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCAG... 4          0.536709
TTCGCCGACGCCACCCAGGCCGCCCTGCAGGCCGGCATTCCCTTCAG... 1          0.428382
                                                   2          0.428733
                                                   3          0.961859
                                                   4          0.610398

timepoint                                                           24  \
metric                                                 bc_activity_avg
AD                                                 rep
ACCGACGCCATCGACGAGGAGGTGGCCATGAGCGCCGTGATCGAGAT... 1               inf
                                                   2          0.460526
                                                   3          0.900000
                                                   4          0.216981
ACCGACTTCATCGACGAGGAGGTGATCATGAGCATCGTGATCGAGAT... 1          0.799833
...                                                                ...
TTCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCAG... 4               inf
TTCGCCGACGCCACCCAGGCCGCCCTGCAGGCCGGCATTCCCTTCAG... 1          1.230835
                                                   2               inf
                                                   3               inf
                                                   4          5.255118

timepoint                                                               \
metric                                                 bc_activity_std
AD                                                 rep
ACCGACGCCATCGACGAGGAGGTGGCCATGAGCGCCGTGATCGAGAT... 1               NaN
                                                   2               NaN
                                                   3               NaN
                                                   4               NaN
ACCGACTTCATCGACGAGGAGGTGATCATGAGCATCGTGATCGAGAT... 1          0.881567
...                                                                ...
TTCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCAG... 4               NaN
TTCGCCGACGCCACCCAGGCCGCCCTGCAGGCCGGCATTCCCTTCAG... 1          0.362868
                                                   2               NaN
                                                   3               NaN
                                                   4          9.293139

timepoint                                                               \
metric                                                 pooled_activity
AD                                                 rep
ACCGACGCCATCGACGAGGAGGTGGCCATGAGCGCCGTGATCGAGAT... 1               inf
                                                   2          0.460526
                                                   3          0.900000
                                                   4          0.216981
ACCGACTTCATCGACGAGGAGGTGATCATGAGCATCGTGATCGAGAT... 1          1.407127
...                                                                ...
TTCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCAG... 4          0.876188
TTCGCCGACGCCACCCAGGCCGCCCTGCAGGCCGGCATTCCCTTCAG... 1          1.158668
                                                   2          1.602429
                                                   3          1.148434
                                                   4          1.335161

timepoint                                                           48  \
metric                                                 bc_activity_avg
AD                                                 rep
ACCGACGCCATCGACGAGGAGGTGGCCATGAGCGCCGTGATCGAGAT... 1               NaN
                                                   2          0.322388
                                                   3          0.000000
                                                   4          0.800000
ACCGACTTCATCGACGAGGAGGTGATCATGAGCATCGTGATCGAGAT... 1               inf
...                                                                ...
TTCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCAG... 4               inf
TTCGCCGACGCCACCCAGGCCGCCCTGCAGGCCGGCATTCCCTTCAG... 1               inf
                                                   2               inf
                                                   3               inf
                                                   4          3.718871

timepoint                                                               \
metric                                                 bc_activity_std
AD                                                 rep
ACCGACGCCATCGACGAGGAGGTGGCCATGAGCGCCGTGATCGAGAT... 1               NaN
                                                   2               NaN
                                                   3               NaN
                                                   4               NaN
ACCGACTTCATCGACGAGGAGGTGATCATGAGCATCGTGATCGAGAT... 1               NaN
...                                                                ...
TTCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCAG... 4               NaN
TTCGCCGACGCCACCCAGGCCGCCCTGCAGGCCGGCATTCCCTTCAG... 1               NaN
                                                   2               NaN
                                                   3               NaN
                                                   4          8.022133

timepoint
metric                                                 pooled_activity
AD                                                 rep
ACCGACGCCATCGACGAGGAGGTGGCCATGAGCGCCGTGATCGAGAT... 1               NaN
                                                   2          0.322388
                                                   3          0.000000
                                                   4          0.800000
ACCGACTTCATCGACGAGGAGGTGATCATGAGCATCGTGATCGAGAT... 1               inf
...                                                                ...
TTCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCAG... 4          0.569870
TTCGCCGACGCCACCCAGGCCGCCCTGCAGGCCGGCATTCCCTTCAG... 1       1493.500000
                                                   2          1.055864
                                                   3          0.573390
                                                   4          0.737480

[897 rows x 12 columns]

In [12]:
puro_no_err_corr_trebl_exp_bc = pd.read_csv("/global/scratch/projects/fc_mvslab/OpenProjects/Sanjana/TREBL/output/NKX2-2/TL4B2/puro_only/no_err_corr/bc_activities.csv",
                                        header = 0)
puro_no_err_corr_trebl_exp_bc

,ADBC2,HawkBCs,RTBC,AD,time,rep,AD_umi_count_simple,RTBC_umi_count_simple,activity
0,AAAAAA,ATTCTCGCC,CTGGAATGACATAGGG,GCCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCG...,0,1,0.0,1.0,inf
1,AAAAAA,ATTCTCGCC,CTGGAATGACATAGGG,GCCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCG...,0,2,113.0,113.0,1.000000
2,AAAAAA,ATTCTCGCC,CTGGAATGACATAGGG,GCCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCG...,0,3,2.0,24.0,12.000000
3,AAAAAA,ATTCTCGCC,CTGGAATGACATAGGG,GCCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCG...,4,1,0.0,1.0,inf
4,AAAAAA,ATTCTCGCC,CTGGAATGACATAGGG,GCCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCG...,4,2,174.0,212.0,1.218391
...,...,...,...,...,...,...,...,...,...
17444,TTTTTT,AGAGGAGTT,GGATCGTAGGTGCATG,GCCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCA...,24,4,4996.0,4827.0,0.966173
17445,TTTTTT,AGAGGAGTT,GGATCGTAGGTGCATG,GCCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCA...,48,1,2.0,1692.0,846.000000
17446,TTTTTT,AGAGGAGTT,GGATCGTAGGTGCATG,GCCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCA...,48,2,9995.0,5208.0,0.521061
17447,TTTTTT,AGAGGAGTT,GGATCGTAGGTGCATG,GCCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCA...,48,3,3724.0,3170.0,0.851235
17448,TTTTTT,AGAGGAGTT,GGATCGTAGGTGCATG,GCCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCA...,48,4,5815.0,5007.0,0.861049

In [16]:
puro_no_err_corr_trebl_exp_bc_0 = puro_no_err_corr_trebl_exp_bc[puro_no_err_corr_trebl_exp_bc['time'] == 0]

In [17]:
puro_no_err_corr_trebl_exp_bc_0[puro_no_err_corr_trebl_exp_bc_0["RTBC_umi_count_simple"] == 11]

,ADBC2,HawkBCs,RTBC,AD,time,rep,AD_umi_count_simple,RTBC_umi_count_simple,activity
70,AAAACC,ATGCTCAGT,ATAACTATCCTCCGCC,GCCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCA...,0,4,1.0,11.0,11.000000
171,AAAATA,ACCTGGAAC,AAGCAAAGTACCCAAA,GCCCAGGACCTGGCCAGCGCCACCTTCCAGGCCGGCATTCCCTTCA...,0,1,2.0,11.0,5.500000
781,AACAGC,CAGCGGTAT,ATCTAGAAAAAACAAC,GCCCAGGACCTGGACGACGACACCTTCCAGGCCGGCATTCCCTTCA...,0,4,313.0,11.0,0.035144
1062,AAGAAA,AAGCCAACT,AAAGCGAAAAGAGATA,GCCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCA...,0,1,30.0,11.0,0.366667
1336,AAGGCA,CACGAGATC,CCGCGAGTCACGATAA,GCCGAGGACCTGGCCGCCGCCACCTTCGAGGCCGGCATTCCCTTCA...,0,3,1.0,11.0,11.000000
...,...,...,...,...,...,...,...,...,...
16698,TTCGGA,AGTGCCGAA,GATAGTGCTAAATAAG,GCCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCA...,0,3,7.0,11.0,1.571429
16714,TTCGGA,AGTGCCGAA,GATAGTGCTAAATAAG,GCCCAGGCCCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCA...,0,3,7.0,11.0,1.571429
16842,TTGAGT,CCATCGGTT,ACATGTCATTTTAATC,GACTCTCCCGGACCCGGCTTCACACCTCACGACAGCGCTCCCGCCG...,0,3,962.0,11.0,0.011435
17241,TTTCGA,AATGCAGTC,TATCAAGAAGACAACT,GCCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCA...,0,4,1.0,11.0,11.000000
17359,TTTGGT,CAAGTCTGG,TAGAAAAAAATCGAAA,GCCCAGGAGCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCA...,0,4,2.0,11.0,5.500000

In [27]:
dup_rows = puro_no_err_corr_trebl_exp_bc[
    puro_no_err_corr_trebl_exp_bc
        .groupby(["rep", "time", "AD", "RTBC_umi_count_simple"])["AD"]
        .transform("size") > 1
]

dup_rows = dup_rows.sort_values(by = ["AD", "rep", "time"])
dup_rows

,ADBC2,HawkBCs,RTBC,AD,time,rep,AD_umi_count_simple,RTBC_umi_count_simple,activity
3073,ACGTTA,CCAACACTA,AATTAAATTTAAAGAG,ACCGACTTCATCGACGAGGAGGTGCTGATGAGCCTGGTGATCGAGA...,0,1,17.0,12.0,0.705882
9517,GAAATC,CCAACACTA,GCATAAACCCGATATA,ACCGACTTCATCGACGAGGAGGTGCTGATGAGCCTGGTGATCGAGA...,0,1,3.0,12.0,4.000000
4978,ATAGAT,CCAACACTA,TGTTGTTTGCCCATGA,ACCGACTTCATCGACGAGGAGGTGCTGATGAGCCTGGTGATCGAGA...,4,1,0.0,1.0,inf
7538,CCGCTG,CCAACACTA,AAACAATATTTTAAGA,ACCGACTTCATCGACGAGGAGGTGCTGATGAGCCTGGTGATCGAGA...,4,1,0.0,1.0,inf
4980,ATAGAT,CCAACACTA,TGTTGTTTGCCCATGA,ACCGACTTCATCGACGAGGAGGTGCTGATGAGCCTGGTGATCGAGA...,4,3,14.0,0.0,0.000000
...,...,...,...,...,...,...,...,...,...
7490,CCGCGT,AACGTCACT,AAGAAGCTAATAGCAA,TTCGCCGACGCCACCCAGGCCGCCCTGCAGGCCGGCATTCCCTTCA...,0,3,1.0,1.0,1.000000
10764,GCAACC,AACGTCACT,CGCTTTAATTTCGACA,TTCGCCGACGCCACCCAGGCCGCCCTGCAGGCCGGCATTCCCTTCA...,0,3,7.0,7.0,1.000000
12085,GGTTTC,AACGTCACT,TTGCCTAACTGTTTGC,TTCGCCGACGCCACCCAGGCCGCCCTGCAGGCCGGCATTCCCTTCA...,0,3,0.0,1.0,inf
3219,ACTCCC,AACGTCACT,GTGCTAAACTTTGTAA,TTCGCCGACGCCACCCAGGCCGCCCTGCAGGCCGGCATTCCCTTCA...,0,4,2.0,6.0,3.000000
7491,CCGCGT,AACGTCACT,AAGAAGCTAATAGCAA,TTCGCCGACGCCACCCAGGCCGCCCTGCAGGCCGGCATTCCCTTCA...,0,4,0.0,6.0,inf

In [33]:
problem_cases_with_bcs = (
    puro_no_err_corr_trebl_exp_bc
        .groupby(["rep", "time", "AD", "RTBC"])
        .agg(
            n_rows=("AD", "size"),
            n_ADBC2=("ADBC2", "nunique"),
            n_HawkBC=("HawkBCs", "nunique"),
            ADBC2s=("ADBC2", lambda x: sorted(x.unique())),
            HawkBCs=("HawkBCs", lambda x: sorted(x.unique())),
        )
        .reset_index()
        .query("n_ADBC2 > 1 or n_HawkBC > 1")
)

problem_cases_with_bcs

,rep,time,AD,RTBC,n_rows,n_ADBC2,n_HawkBC,ADBC2s,HawkBCs
82,1,0,CCCACCGACGTGAGCCTGGGCGACGAGCTGCACCTGGACGGCGAGG...,GATGGGAATAAATGGC,2,2,1,"[ATCACA, GTAGGT]",[CCACCTTAC]
477,1,0,GCCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCA...,AGTAATATAAGGGTAA,2,2,1,"[AAAACC, ACTGGG]",[AAGCTGCGA]
980,1,0,TTCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCA...,GCCGATGCTTATTTAT,2,2,1,"[GGAGAC, TTGTGC]",[AGCACAGGA]
1079,1,4,CCCACCGACGTGAGCCTGGGCGACGAGCTGCACCTGGACGGCGAGG...,GATGGGAATAAATGGC,2,2,1,"[ATCACA, GTAGGT]",[CCACCTTAC]
1516,1,4,GCCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCA...,AGTAATATAAGGGTAA,2,2,1,"[AAAACC, ACTGGG]",[AAGCTGCGA]
2083,1,4,TTCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCA...,GCCGATGCTTATTTAT,2,2,1,"[GGAGAC, TTGTGC]",[AGCACAGGA]
2189,1,24,CCCACCGACGTGAGCCTGGGCGACGAGCTGCACCTGGACGGCGAGG...,GATGGGAATAAATGGC,2,2,1,"[ATCACA, GTAGGT]",[CCACCTTAC]
2623,1,24,GCCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCA...,AGTAATATAAGGGTAA,2,2,1,"[AAAACC, ACTGGG]",[AAGCTGCGA]
3149,1,24,TTCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCA...,GCCGATGCTTATTTAT,2,2,1,"[GGAGAC, TTGTGC]",[AGCACAGGA]
3236,1,48,CCCACCGACGTGAGCCTGGGCGACGAGCTGCACCTGGACGGCGAGG...,GATGGGAATAAATGGC,2,2,1,"[ATCACA, GTAGGT]",[CCACCTTAC]
3632,1,48,GCCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCA...,AGTAATATAAGGGTAA,2,2,1,"[AAAACC, ACTGGG]",[AAGCTGCGA]
4131,1,48,TTCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCA...,GCCGATGCTTATTTAT,2,2,1,"[GGAGAC, TTGTGC]",[AGCACAGGA]
4224,2,0,CCCACCGACGTGAGCCTGGGCGACGAGCTGCACCTGGACGGCGAGG...,GATGGGAATAAATGGC,2,2,1,"[ATCACA, GTAGGT]",[CCACCTTAC]
4628,2,0,GCCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCA...,AGTAATATAAGGGTAA,2,2,1,"[AAAACC, ACTGGG]",[AAGCTGCGA]
5143,2,0,TTCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCA...,GCCGATGCTTATTTAT,2,2,1,"[GGAGAC, TTGTGC]",[AGCACAGGA]
5242,2,4,CCCACCGACGTGAGCCTGGGCGACGAGCTGCACCTGGACGGCGAGG...,GATGGGAATAAATGGC,2,2,1,"[ATCACA, GTAGGT]",[CCACCTTAC]
5672,2,4,GCCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCA...,AGTAATATAAGGGTAA,2,2,1,"[AAAACC, ACTGGG]",[AAGCTGCGA]
6226,2,4,TTCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCA...,GCCGATGCTTATTTAT,2,2,1,"[GGAGAC, TTGTGC]",[AGCACAGGA]
6326,2,24,CCCACCGACGTGAGCCTGGGCGACGAGCTGCACCTGGACGGCGAGG...,GATGGGAATAAATGGC,2,2,1,"[ATCACA, GTAGGT]",[CCACCTTAC]
6762,2,24,GCCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCA...,AGTAATATAAGGGTAA,2,2,1,"[AAAACC, ACTGGG]",[AAGCTGCGA]
7314,2,24,TTCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCA...,GCCGATGCTTATTTAT,2,2,1,"[GGAGAC, TTGTGC]",[AGCACAGGA]
7415,2,48,CCCACCGACGTGAGCCTGGGCGACGAGCTGCACCTGGACGGCGAGG...,GATGGGAATAAATGGC,2,2,1,"[ATCACA, GTAGGT]",[CCACCTTAC]
7845,2,48,GCCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCA...,AGTAATATAAGGGTAA,2,2,1,"[AAAACC, ACTGGG]",[AAGCTGCGA]
8387,2,48,TTCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCA...,GCCGATGCTTATTTAT,2,2,1,"[GGAGAC, TTGTGC]",[AGCACAGGA]
8471,3,0,CCCACCGACGTGAGCCTGGGCGACGAGCTGCACCTGGACGGCGAGG...,GATGGGAATAAATGGC,2,2,1,"[ATCACA, GTAGGT]",[CCACCTTAC]
9395,3,0,TTCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCA...,GCCGATGCTTATTTAT,2,2,1,"[GGAGAC, TTGTGC]",[AGCACAGGA]
9504,3,4,CCCACCGACGTGAGCCTGGGCGACGAGCTGCACCTGGACGGCGAGG...,GATGGGAATAAATGGC,2,2,1,"[ATCACA, GTAGGT]",[CCACCTTAC]
9976,3,4,GCCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCA...,AGTAATATAAGGGTAA,2,2,1,"[AAAACC, ACTGGG]",[AAGCTGCGA]
10591,3,4,TTCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCA...,GCCGATGCTTATTTAT,2,2,1,"[GGAGAC, TTGTGC]",[AGCACAGGA]
10695,3,24,CCCACCGACGTGAGCCTGGGCGACGAGCTGCACCTGGACGGCGAGG...,GATGGGAATAAATGGC,2,2,1,"[ATCACA, GTAGGT]",[CCACCTTAC]
11138,3,24,GCCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCA...,AGTAATATAAGGGTAA,2,2,1,"[AAAACC, ACTGGG]",[AAGCTGCGA]
11702,3,24,TTCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCA...,GCCGATGCTTATTTAT,2,2,1,"[GGAGAC, TTGTGC]",[AGCACAGGA]
11802,3,48,CCCACCGACGTGAGCCTGGGCGACGAGCTGCACCTGGACGGCGAGG...,GATGGGAATAAATGGC,2,2,1,"[ATCACA, GTAGGT]",[CCACCTTAC]
12772,3,48,TTCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCA...,GCCGATGCTTATTTAT,2,2,1,"[GGAGAC, TTGTGC]",[AGCACAGGA]
12869,4,0,CCCACCGACGTGAGCCTGGGCGACGAGCTGCACCTGGACGGCGAGG...,GATGGGAATAAATGGC,2,2,1,"[ATCACA, GTAGGT]",[CCACCTTAC]
13310,4,0,GCCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCA...,AGTAATATAAGGGTAA,2,2,1,"[AAAACC, ACTGGG]",[AAGCTGCGA]
14002,4,4,CCCACCGACGTGAGCCTGGGCGACGAGCTGCACCTGGACGGCGAGG...,GATGGGAATAAATGGC,2,2,1,"[ATCACA, GTAGGT]",[CCACCTTAC]
14471,4,4,GCCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCA...,AGTAATATAAGGGTAA,2,2,1,"[AAAACC, ACTGGG]",[AAGCTGCGA]
15090,4,4,TTCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCA...,GCCGATGCTTATTTAT,2,2,1,"[GGAGAC, TTGTGC]",[AGCACAGGA]
15197,4,24,CCCACCGACGTGAGCCTGGGCGACGAGCTGCACCTGGACGGCGAGG...,GATGGGAATAAATGGC,2,2,1,"[ATCACA, GTAGGT]",[CCACCTTAC]
15663,4,24,GCCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCA...,AGTAATATAAGGGTAA,2,2,1,"[AAAACC, ACTGGG]",[AAGCTGCGA]
16260,4,24,TTCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCA...,GCCGATGCTTATTTAT,2,2,1,"[GGAGAC, TTGTGC]",[AGCACAGGA]
16364,4,48,CCCACCGACGTGAGCCTGGGCGACGAGCTGCACCTGGACGGCGAGG...,GATGGGAATAAATGGC,2,2,1,"[ATCACA, GTAGGT]",[CCACCTTAC]
16809,4,48,GCCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCA...,AGTAATATAAGGGTAA,2,2,1,"[AAAACC, ACTGGG]",[AAGCTGCGA]
17393,4,48,TTCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCA...,GCCGATGCTTATTTAT,2,2,1,"[GGAGAC, TTGTGC]",[AGCACAGGA]

In [28]:
dup_rows[dup_rows["RTBC_umi_count_simple"] == 111]

,ADBC2,HawkBCs,RTBC,AD,time,rep,AD_umi_count_simple,RTBC_umi_count_simple,activity
5206,ATCAGA,CATTCGTAC,GACTTGAAACTGAATA,ACCGACTTCATCGACGAGGAGGTGTTCATGAGCTTCGTGATCGAGA...,24,1,79.0,111.0,1.405063
7304,CCATAC,CATTCGTAC,CCAATTGAGTGCCTAG,ACCGACTTCATCGACGAGGAGGTGTTCATGAGCTTCGTGATCGAGA...,24,1,433.0,111.0,0.256351

# Step 1

In [63]:
step1 = pd.read_csv("../../output/NKX2-2/pipeline_test/no_err_corr/step1.csv")
step1

,ADBC2,HawkBCs,RTBC,AD,count,ADBC2_qual,HawkBCs_qual,RTBC_qual,AD_qual,Designed
0,CTAGAA,CAATGTGAC,CCACGATGTAACTTCT,GCCGACGACCTGGCCGCCGCCACCTTCGACGCCGGCATTCCCTTCA...,4970,True,True,True,True,1
1,TGTGAT,AGTTAGTGG,GCGATCGTAATCACCA,GCCCAGGACCTGGCCGCCGCCACCCTGCAGGCCGGCATTCCTCTGA...,4146,True,True,True,True,1
2,AAGCTC,ACAAGCCAC,AAGTGAACAACACTGC,GCCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCA...,4113,True,True,True,True,1
3,CAGACT,ACAACAGAC,GCCAAAAGGGTATACG,GCCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCA...,4021,True,True,True,True,1
4,CACGAA,CAACTACAG,TAATTTAAACTAAAGA,GCCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCA...,3816,True,True,True,True,1
...,...,...,...,...,...,...,...,...,...,...
1560,CCGACG,AGGACAAGT,CCTAAGACCTAACTCA,CAGTACAACGCCCAGTACAGCAGCGCCAGCACACCTCAGGCCCAGG...,172,True,True,True,True,1
1561,ACTTAT,AATACCACG,GGACGTTCAAGGGGCC,GCCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCA...,166,True,True,True,True,1
1562,TAAGAG,CAGTTACAC,ATAATCAGAAAGCTGA,GCCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCA...,153,True,True,True,True,1
1563,ATGTAT,AACTTGACC,CTTGCCTATCGTACCT,GCCCAGGACCTGGCCGCCGCCACCTTCCAGAGCAGCGGCGCCTACT...,114,True,True,True,True,1
1564,CTATAG,AACAACACC,GTCTTGAGATTTAGGG,GCCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCA...,112,True,True,True,True,1

In [64]:
step1["ADBC"] = step1["HawkBCs"] + step1["ADBC2"]
step1

,ADBC2,HawkBCs,RTBC,AD,count,ADBC2_qual,HawkBCs_qual,RTBC_qual,AD_qual,Designed,ADBC
0,CTAGAA,CAATGTGAC,CCACGATGTAACTTCT,GCCGACGACCTGGCCGCCGCCACCTTCGACGCCGGCATTCCCTTCA...,4970,True,True,True,True,1,CAATGTGACCTAGAA
1,TGTGAT,AGTTAGTGG,GCGATCGTAATCACCA,GCCCAGGACCTGGCCGCCGCCACCCTGCAGGCCGGCATTCCTCTGA...,4146,True,True,True,True,1,AGTTAGTGGTGTGAT
2,AAGCTC,ACAAGCCAC,AAGTGAACAACACTGC,GCCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCA...,4113,True,True,True,True,1,ACAAGCCACAAGCTC
3,CAGACT,ACAACAGAC,GCCAAAAGGGTATACG,GCCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCA...,4021,True,True,True,True,1,ACAACAGACCAGACT
4,CACGAA,CAACTACAG,TAATTTAAACTAAAGA,GCCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCA...,3816,True,True,True,True,1,CAACTACAGCACGAA
...,...,...,...,...,...,...,...,...,...,...,...
1560,CCGACG,AGGACAAGT,CCTAAGACCTAACTCA,CAGTACAACGCCCAGTACAGCAGCGCCAGCACACCTCAGGCCCAGG...,172,True,True,True,True,1,AGGACAAGTCCGACG
1561,ACTTAT,AATACCACG,GGACGTTCAAGGGGCC,GCCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCA...,166,True,True,True,True,1,AATACCACGACTTAT
1562,TAAGAG,CAGTTACAC,ATAATCAGAAAGCTGA,GCCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCA...,153,True,True,True,True,1,CAGTTACACTAAGAG
1563,ATGTAT,AACTTGACC,CTTGCCTATCGTACCT,GCCCAGGACCTGGCCGCCGCCACCTTCCAGAGCAGCGGCGCCTACT...,114,True,True,True,True,1,AACTTGACCATGTAT
1564,CTATAG,AACAACACC,GTCTTGAGATTTAGGG,GCCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCA...,112,True,True,True,True,1,AACAACACCCTATAG

In [65]:
step1 = pd.merge(step1, pd.DataFrame(step1[["RTBC", "AD"]].drop_duplicates().value_counts()).reset_index(), on = ["RTBC", "AD"], suffixes = ("", "_RTBCs"))
step1

,ADBC2,HawkBCs,RTBC,AD,count,ADBC2_qual,HawkBCs_qual,RTBC_qual,AD_qual,Designed,ADBC,count_RTBCs
0,CTAGAA,CAATGTGAC,CCACGATGTAACTTCT,GCCGACGACCTGGCCGCCGCCACCTTCGACGCCGGCATTCCCTTCA...,4970,True,True,True,True,1,CAATGTGACCTAGAA,1
1,TGTGAT,AGTTAGTGG,GCGATCGTAATCACCA,GCCCAGGACCTGGCCGCCGCCACCCTGCAGGCCGGCATTCCTCTGA...,4146,True,True,True,True,1,AGTTAGTGGTGTGAT,1
2,AAGCTC,ACAAGCCAC,AAGTGAACAACACTGC,GCCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCA...,4113,True,True,True,True,1,ACAAGCCACAAGCTC,1
3,CAGACT,ACAACAGAC,GCCAAAAGGGTATACG,GCCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCA...,4021,True,True,True,True,1,ACAACAGACCAGACT,1
4,CACGAA,CAACTACAG,TAATTTAAACTAAAGA,GCCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCA...,3816,True,True,True,True,1,CAACTACAGCACGAA,1
...,...,...,...,...,...,...,...,...,...,...,...,...
1560,CCGACG,AGGACAAGT,CCTAAGACCTAACTCA,CAGTACAACGCCCAGTACAGCAGCGCCAGCACACCTCAGGCCCAGG...,172,True,True,True,True,1,AGGACAAGTCCGACG,1
1561,ACTTAT,AATACCACG,GGACGTTCAAGGGGCC,GCCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCA...,166,True,True,True,True,1,AATACCACGACTTAT,1
1562,TAAGAG,CAGTTACAC,ATAATCAGAAAGCTGA,GCCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCA...,153,True,True,True,True,1,CAGTTACACTAAGAG,1
1563,ATGTAT,AACTTGACC,CTTGCCTATCGTACCT,GCCCAGGACCTGGCCGCCGCCACCTTCCAGAGCAGCGGCGCCTACT...,114,True,True,True,True,1,AACTTGACCATGTAT,1
1564,CTATAG,AACAACACC,GTCTTGAGATTTAGGG,GCCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCA...,112,True,True,True,True,1,AACAACACCCTATAG,1

In [66]:
step1["count_RTBCs"].value_counts()

count_RTBCs
1    1565
Name: count, dtype: int64

In [67]:
mismatch_rows = pd.read_excel("../../data/mismatch_rows.xlsx")
mismatch_rows

,HawkBCs,RTBC,AD,ADBC2,time,rep,AD_umi_count_simple_pseudo,RTBC_umi_count_simple_pseudo
0,AACACCTCA,GAGATCTTCTTGGAGC,CTGCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCA...,TGCGAC,0,1,3,1
1,AACACCTCA,GAGATCTTCTTGGAGC,CTGCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCA...,TGCGAC,0,2,1947,1031
2,AACACCTCA,GAGATCTTCTTGGAGC,CTGCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCA...,TGCGAC,0,3,2,1
3,AACACCTCA,GAGATCTTCTTGGAGC,CTGCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCA...,TGCGAC,0,4,12874,4972
4,AACACCTCA,GAGATCTTCTTGGAGC,CTGCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCA...,TGCGAC,-1,2,24,235
...,...,...,...,...,...,...,...,...
953,CAGCGGTAT,CCCCAGGCACTATAAG,GCCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCA...,GTAATC,48,4,1124,2
954,CAGCGGTAT,CCCCAGGCACTATAAG,GCCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCA...,GTAATC,6,1,3049,6133
955,CAGCGGTAT,CCCCAGGCACTATAAG,GCCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCA...,GTAATC,6,2,6234,4014
956,CAGCGGTAT,CCCCAGGCACTATAAG,GCCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCA...,GTAATC,6,3,2924,2962
957,CAGCGGTAT,CCCCAGGCACTATAAG,GCCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCA...,GTAATC,6,4,1353,994

In [68]:
step1[step1["RTBC"] == "GAGATCTTCTTGGAGC"]#["AD"]#.value_counts()

,ADBC2,HawkBCs,RTBC,AD,count,ADBC2_qual,HawkBCs_qual,RTBC_qual,AD_qual,Designed,ADBC,count_RTBCs
1493,TGCGAC,AACACCTCA,GAGATCTTCTTGGAGC,CTGCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCA...,2145,True,True,True,True,1,AACACCTCATGCGAC,1

In [80]:
bc_activities = pd.read_csv("/global/scratch/projects/fc_mvslab/OpenProjects/Sanjana/TREBL/output/NKX2-2/TL4B2/rim/no_err_corr/bc_activities.csv")
bc_activities

,ADBC2,HawkBCs,RTBC,AD,time,rep,AD_umi_count_simple,RTBC_umi_count_simple,activity
0,AAAAAA,ATTCTCGCC,CTGGAATGACATAGGG,GCCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCG...,0,1,196.0,81.0,0.413265
1,AAAAAA,ATTCTCGCC,CTGGAATGACATAGGG,GCCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCG...,0,2,1529.0,1159.0,0.758012
2,AAAAAA,ATTCTCGCC,CTGGAATGACATAGGG,GCCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCG...,0,3,0.0,1.0,inf
3,AAAAAA,ATTCTCGCC,CTGGAATGACATAGGG,GCCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCG...,0ND,1,5.0,22.0,4.400000
4,AAAAAA,ATTCTCGCC,CTGGAATGACATAGGG,GCCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCG...,0ND,2,21.0,182.0,8.666667
...,...,...,...,...,...,...,...,...,...
17838,TTTTGC,ATACCGTCG,AAATCGTAGACGTTAC,GCCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATCAGCTTCA...,0,4,2.0,0.0,0.000000
17839,TTTTGC,ATACCGTCG,AAATCGTAGACGTTAC,GCCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATCAGCTTCA...,24,2,1.0,0.0,0.000000
17840,TTTTGC,ATACCGTCG,AAATCGTAGACGTTAC,GCCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATCAGCTTCA...,24,3,1.0,0.0,0.000000
17841,TTTTGC,ATACCGTCG,AAATCGTAGACGTTAC,GCCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATCAGCTTCA...,4,1,1.0,0.0,0.000000
17842,TTTTGC,ATACCGTCG,AAATCGTAGACGTTAC,GCCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATCAGCTTCA...,48,4,3.0,0.0,0.000000

In [81]:
bc_activities[bc_activities["RTBC"] == "GAGATCTTCTTGGAGC"]["AD"].value_counts()

AD
CTGCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCAGCGCCTACAGCGCCCAGAGCCTGCAGCACATGCAGTACAACGCCCAGTACAGCAGCGCCAGCACACCTCAGTATCCCACCGCCCATCCTCTGGTGCAGGCCCAGCAGTGGACCTGG    17
Name: count, dtype: int64