In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import pandas as pd
import numpy as np
# import matplotlib.pyplot as plt
# import seaborn as sns
# from concurrent.futures import ThreadPoolExecutor, as_completed
# import dask.dataframe as dd
# import sys
# import glob
# import os

from trebl_tools import (
    initial_map,
    map_refiner,
    complexity,
    finder,
    preprocess,
    error_correct,
    plotting,
    umi_deduplicate,
    pipelines,
)


from tqdm import tqdm  # progress bar

In [3]:
trebl_exp_ADBC2 = finder.Barcode(
    name="ADBC2", preceder="TATGCTAT", post="GGCCGGCCG", length=6
)

trebl_exp_HawkBCs = finder.Barcode(
    name="HawkBCs", preceder="TAGC", post="CTCGAGA", length=9
)
trebl_exp_RTBC = finder.Barcode(name="RTBC", preceder="GCCCC", post="GCGG", length=16)

# 1. Puro only, no err corr

In [4]:
pipeline_no_err_corr_puro_only = pipelines.TreblPipeline(
    db_path="",
    design_file_path="",
    error_correction=False,
    output_path="../../output/NKX2-2/TL4B2/puro_only/no_err_corr",
)

In [5]:
puro_only_activities = pipeline_no_err_corr_puro_only.calculate_activity_scores(
    step1_path="../../output/NKX2-2/pipeline_test/no_err_corr/step1.csv",
    AD_bc_objects=[trebl_exp_ADBC2, trebl_exp_HawkBCs],
    RT_bc_objects=[trebl_exp_RTBC],
    time_regex=r"_T(\d+)_",
    rep_regex=r"_R(\d+)_",
)

In [6]:
puro_only_activities

timepoint                                                            0  \
metric                                                 bc_activity_avg
AD                                                 rep
ACCGACGCCATCGACGAGGAGGTGGCCATGAGCGCCGTGATCGAGAT... 1               NaN
                                                   2               inf
                                                   3               NaN
                                                   4               NaN
ACCGACTTCATCGACGAGGAGGTGATCATGAGCATCGTGATCGAGAT... 1          6.513889
...                                                                ...
TTCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCAG... 4               inf
TTCGCCGACGCCACCCAGGCCGCCCTGCAGGCCGGCATTCCCTTCAG... 1               inf
                                                   2               inf
                                                   3               inf
                                                   4               inf

timepoint                                                               \
metric                                                 bc_activity_std
AD                                                 rep
ACCGACGCCATCGACGAGGAGGTGGCCATGAGCGCCGTGATCGAGAT... 1               NaN
                                                   2               NaN
                                                   3               NaN
                                                   4               NaN
ACCGACTTCATCGACGAGGAGGTGATCATGAGCATCGTGATCGAGAT... 1          9.172746
...                                                                ...
TTCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCAG... 4               NaN
TTCGCCGACGCCACCCAGGCCGCCCTGCAGGCCGGCATTCCCTTCAG... 1               NaN
                                                   2               NaN
                                                   3               NaN
                                                   4               NaN

timepoint                                                               \
metric                                                 pooled_activity
AD                                                 rep
ACCGACGCCATCGACGAGGAGGTGGCCATGAGCGCCGTGATCGAGAT... 1               NaN
                                                   2               inf
                                                   3               NaN
                                                   4               NaN
ACCGACTTCATCGACGAGGAGGTGATCATGAGCATCGTGATCGAGAT... 1          0.205479
...                                                                ...
TTCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCAG... 4          1.468085
TTCGCCGACGCCACCCAGGCCGCCCTGCAGGCCGGCATTCCCTTCAG... 1          9.200000
                                                   2          0.250229
                                                   3          4.128205
                                                   4          1.477612

timepoint                                                           24  \
metric                                                 bc_activity_avg
AD                                                 rep
ACCGACGCCATCGACGAGGAGGTGGCCATGAGCGCCGTGATCGAGAT... 1               inf
                                                   2          0.460526
                                                   3          0.900000
                                                   4          0.216981
ACCGACTTCATCGACGAGGAGGTGATCATGAGCATCGTGATCGAGAT... 1          0.799833
...                                                                ...
TTCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCAG... 4               inf
TTCGCCGACGCCACCCAGGCCGCCCTGCAGGCCGGCATTCCCTTCAG... 1          1.230835
                                                   2               inf
                                                   3               inf
                                                   4          5.255118

timepoint                                                               \
metric                                                 bc_activity_std
AD                                                 rep
ACCGACGCCATCGACGAGGAGGTGGCCATGAGCGCCGTGATCGAGAT... 1               NaN
                                                   2               NaN
                                                   3               NaN
                                                   4               NaN
ACCGACTTCATCGACGAGGAGGTGATCATGAGCATCGTGATCGAGAT... 1          0.881567
...                                                                ...
TTCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCAG... 4               NaN
TTCGCCGACGCCACCCAGGCCGCCCTGCAGGCCGGCATTCCCTTCAG... 1          0.362868
                                                   2               NaN
                                                   3               NaN
                                                   4          9.293139

timepoint                                                               \
metric                                                 pooled_activity
AD                                                 rep
ACCGACGCCATCGACGAGGAGGTGGCCATGAGCGCCGTGATCGAGAT... 1               inf
                                                   2          0.460526
                                                   3          0.900000
                                                   4          0.216981
ACCGACTTCATCGACGAGGAGGTGATCATGAGCATCGTGATCGAGAT... 1          1.407127
...                                                                ...
TTCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCAG... 4          0.864608
TTCGCCGACGCCACCCAGGCCGCCCTGCAGGCCGGCATTCCCTTCAG... 1          1.158668
                                                   2          1.602429
                                                   3          1.148434
                                                   4          1.335161

timepoint                                                            4  \
metric                                                 bc_activity_avg
AD                                                 rep
ACCGACGCCATCGACGAGGAGGTGGCCATGAGCGCCGTGATCGAGAT... 1               NaN
                                                   2          0.215686
                                                   3          0.807692
                                                   4          1.363636
ACCGACTTCATCGACGAGGAGGTGATCATGAGCATCGTGATCGAGAT... 1          0.209914
...                                                                ...
TTCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCAG... 4               inf
TTCGCCGACGCCACCCAGGCCGCCCTGCAGGCCGGCATTCCCTTCAG... 1               inf
                                                   2               inf
                                                   3               inf
                                                   4               inf

timepoint                                                               \
metric                                                 bc_activity_std
AD                                                 rep
ACCGACGCCATCGACGAGGAGGTGGCCATGAGCGCCGTGATCGAGAT... 1               NaN
                                                   2               NaN
                                                   3               NaN
                                                   4               NaN
ACCGACTTCATCGACGAGGAGGTGATCATGAGCATCGTGATCGAGAT... 1          0.275436
...                                                                ...
TTCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCAG... 4               NaN
TTCGCCGACGCCACCCAGGCCGCCCTGCAGGCCGGCATTCCCTTCAG... 1               NaN
                                                   2               NaN
                                                   3               NaN
                                                   4               NaN

timepoint                                                               \
metric                                                 pooled_activity
AD                                                 rep
ACCGACGCCATCGACGAGGAGGTGGCCATGAGCGCCGTGATCGAGAT... 1               NaN
                                                   2          0.215686
                                                   3          0.807692
                                                   4          1.363636
ACCGACTTCATCGACGAGGAGGTGATCATGAGCATCGTGATCGAGAT... 1          0.363344
...                                                                ...
TTCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCAG... 4          0.516456
TTCGCCGACGCCACCCAGGCCGCCCTGCAGGCCGGCATTCCCTTCAG... 1          0.428382
                                                   2          0.428733
                                                   3          0.961859
                                                   4          0.610398

timepoint                                                           48  \
metric                                                 bc_activity_avg
AD                                                 rep
ACCGACGCCATCGACGAGGAGGTGGCCATGAGCGCCGTGATCGAGAT... 1               NaN
                                                   2          0.322388
                                                   3          0.000000
                                                   4          0.800000
ACCGACTTCATCGACGAGGAGGTGATCATGAGCATCGTGATCGAGAT... 1               inf
...                                                                ...
TTCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCAG... 4               inf
TTCGCCGACGCCACCCAGGCCGCCCTGCAGGCCGGCATTCCCTTCAG... 1               inf
                                                   2               inf
                                                   3               inf
                                                   4          3.718871

timepoint                                                               \
metric                                                 bc_activity_std
AD                                                 rep
ACCGACGCCATCGACGAGGAGGTGGCCATGAGCGCCGTGATCGAGAT... 1               NaN
                                                   2               NaN
                                                   3               NaN
                                                   4               NaN
ACCGACTTCATCGACGAGGAGGTGATCATGAGCATCGTGATCGAGAT... 1               NaN
...                                                                ...
TTCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCAG... 4               NaN
TTCGCCGACGCCACCCAGGCCGCCCTGCAGGCCGGCATTCCCTTCAG... 1               NaN
                                                   2               NaN
                                                   3               NaN
                                                   4          8.022133

timepoint
metric                                                 pooled_activity
AD                                                 rep
ACCGACGCCATCGACGAGGAGGTGGCCATGAGCGCCGTGATCGAGAT... 1               NaN
                                                   2          0.322388
                                                   3          0.000000
                                                   4          0.800000
ACCGACTTCATCGACGAGGAGGTGATCATGAGCATCGTGATCGAGAT... 1               inf
...                                                                ...
TTCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCAG... 4          0.569174
TTCGCCGACGCCACCCAGGCCGCCCTGCAGGCCGGCATTCCCTTCAG... 1       1493.500000
                                                   2          1.055864
                                                   3          0.573390
                                                   4          0.737480

[897 rows x 12 columns]

In [ ]:
# time_columns = [col for col in activity_mean.columns if isinstance(col, int)]

# activity_mean['na_count'] = activity_mean.isna().sum(axis=1)

# # Filter rows with no nulls (na_count == 0) and no infinite values
# no_nulls_no_inf = activity_mean[(activity_mean['na_count'] == 0) &
#                                            (~activity_mean[time_columns].isin([float('inf')]).any(axis=1))]

# # Filter rows with no nulls (na_count == 0) and select the first 10 rows
# no_nulls_no_inf_subset = no_nulls_no_inf.sample(10)

# # Select columns corresponding to time points (0-60)
# time_columns = [col for col in activity_mean.columns if isinstance(col, int)]

# # Plot lineplot with 10 subplots
# fig, axes = plt.subplots(2,5, figsize=(12,6), sharex=True, sharey = True, dpi = 300)
# axes = axes.flatten()

# for i, (index, row) in enumerate(no_nulls_no_inf_subset.iterrows()):
#     ax = axes[i]
#     ax.plot(time_columns, row[time_columns], marker='o')
#     ax.set_yscale('log')

# fig.supylabel("Activity")
# fig.supxlabel("Time")

# plt.suptitle("NKX2-2 Activity: Puro Only, No Error Correction")
# sns.despine()
# plt.tight_layout()
# plt.show()

# 2. Rim, no err corr

In [7]:
pipeline_no_err_corr_rim = pipelines.TreblPipeline(
    db_path="",
    design_file_path="",
    error_correction=False,
    output_path="../../output/NKX2-2/TL4B2/rim/no_err_corr",
)

In [8]:
pipeline_no_err_corr_rim.calculate_activity_scores(
    step1_path="../../output/NKX2-2/pipeline_test/no_err_corr/step1.csv",
    AD_bc_objects=[trebl_exp_ADBC2, trebl_exp_HawkBCs],
    RT_bc_objects=[trebl_exp_RTBC],
    time_regex=r"_T([^_]+)_",
    rep_regex=r"R(\d+)",
)

timepoint                                                            0  \
metric                                                 bc_activity_avg
AD                                                 rep
ACCGACTTCATCGACGAGGAGGTGATCATGAGCATCGTGATCGAGAT... 1          0.427641
                                                   2          0.520742
                                                   3          0.419135
                                                   4               inf
ACCGACTTCATCGACGAGGAGGTGCTGATGAGCCTGGTGATCGAGAT... 1          0.265428
...                                                                ...
TTCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCAG... 4          0.387565
TTCGCCGACGCCACCCAGGCCGCCCTGCAGGCCGGCATTCCCTTCAG... 1          0.444535
                                                   2          0.627512
                                                   3               inf
                                                   4               inf

timepoint                                                               \
metric                                                 bc_activity_std
AD                                                 rep
ACCGACTTCATCGACGAGGAGGTGATCATGAGCATCGTGATCGAGAT... 1               NaN
                                                   2          0.010223
                                                   3          0.046774
                                                   4               NaN
ACCGACTTCATCGACGAGGAGGTGCTGATGAGCCTGGTGATCGAGAT... 1          0.182723
...                                                                ...
TTCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCAG... 4          0.038024
TTCGCCGACGCCACCCAGGCCGCCCTGCAGGCCGGCATTCCCTTCAG... 1          0.121147
                                                   2          0.207417
                                                   3               NaN
                                                   4               NaN

timepoint                                                               \
metric                                                 pooled_activity
AD                                                 rep
ACCGACTTCATCGACGAGGAGGTGATCATGAGCATCGTGATCGAGAT... 1          0.427641
                                                   2          0.527727
                                                   3          0.432078
                                                   4          0.564665
ACCGACTTCATCGACGAGGAGGTGCTGATGAGCCTGGTGATCGAGAT... 1          0.269532
...                                                                ...
TTCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCAG... 4          0.362801
TTCGCCGACGCCACCCAGGCCGCCCTGCAGGCCGGCATTCCCTTCAG... 1          0.400706
                                                   2          0.493356
                                                   3          0.789222
                                                   4          2.818015

timepoint                                                          0ND  \
metric                                                 bc_activity_avg
AD                                                 rep
ACCGACTTCATCGACGAGGAGGTGATCATGAGCATCGTGATCGAGAT... 1          5.102132
                                                   2          5.665000
                                                   3          3.919522
                                                   4               inf
ACCGACTTCATCGACGAGGAGGTGCTGATGAGCCTGGTGATCGAGAT... 1               inf
...                                                                ...
TTCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCAG... 4          9.927885
TTCGCCGACGCCACCCAGGCCGCCCTGCAGGCCGGCATTCCCTTCAG... 1          8.058776
                                                   2               inf
                                                   3          8.838969
                                                   4               inf

timepoint                                                               \
metric                                                 bc_activity_std
AD                                                 rep
ACCGACTTCATCGACGAGGAGGTGATCATGAGCATCGTGATCGAGAT... 1               NaN
                                                   2          6.597306
                                                   3          0.732531
                                                   4               NaN
ACCGACTTCATCGACGAGGAGGTGCTGATGAGCCTGGTGATCGAGAT... 1               NaN
...                                                                ...
TTCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCAG... 4          4.565888
TTCGCCGACGCCACCCAGGCCGCCCTGCAGGCCGGCATTCCCTTCAG... 1          4.685207
                                                   2               NaN
                                                   3          8.662133
                                                   4               NaN

timepoint                                                               \
metric                                                 pooled_activity
AD                                                 rep
ACCGACTTCATCGACGAGGAGGTGATCATGAGCATCGTGATCGAGAT... 1          5.102132
                                                   2         10.147059
                                                   3          3.461818
                                                   4          9.266667
ACCGACTTCATCGACGAGGAGGTGCTGATGAGCCTGGTGATCGAGAT... 1          5.518613
...                                                                ...
TTCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCAG... 4         11.046512
TTCGCCGACGCCACCCAGGCCGCCCTGCAGGCCGGCATTCCCTTCAG... 1          8.707602
                                                   2          9.347079
                                                   3         16.286070
                                                   4          9.779661

timepoint                                                           24  \
metric                                                 bc_activity_avg
AD                                                 rep
ACCGACTTCATCGACGAGGAGGTGATCATGAGCATCGTGATCGAGAT... 1          1.825953
                                                   2          1.239305
                                                   3          1.934048
                                                   4               inf
ACCGACTTCATCGACGAGGAGGTGCTGATGAGCCTGGTGATCGAGAT... 1          0.745638
...                                                                ...
TTCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCAG... 4          0.802612
TTCGCCGACGCCACCCAGGCCGCCCTGCAGGCCGGCATTCCCTTCAG... 1               inf
                                                   2          1.043322
                                                   3          2.149543
                                                   4               inf

timepoint                                                               \
metric                                                 bc_activity_std
AD                                                 rep
ACCGACTTCATCGACGAGGAGGTGATCATGAGCATCGTGATCGAGAT... 1               NaN
                                                   2          0.659840
                                                   3          0.102715
                                                   4               NaN
ACCGACTTCATCGACGAGGAGGTGCTGATGAGCCTGGTGATCGAGAT... 1          0.664337
...                                                                ...
TTCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCAG... 4          0.231775
TTCGCCGACGCCACCCAGGCCGCCCTGCAGGCCGGCATTCCCTTCAG... 1               NaN
                                                   2          0.383031
                                                   3          0.385746
                                                   4               NaN

timepoint                                                               \
metric                                                 pooled_activity
AD                                                 rep
ACCGACTTCATCGACGAGGAGGTGATCATGAGCATCGTGATCGAGAT... 1          1.825953
                                                   2          1.690653
                                                   3          1.966258
                                                   4          1.466395
ACCGACTTCATCGACGAGGAGGTGCTGATGAGCCTGGTGATCGAGAT... 1          0.653193
...                                                                ...
TTCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCAG... 4          0.938970
TTCGCCGACGCCACCCAGGCCGCCCTGCAGGCCGGCATTCCCTTCAG... 1          1.415260
                                                   2          0.892234
                                                   3          2.285318
                                                   4          6.988290

timepoint                                                            4  \
metric                                                 bc_activity_avg
AD                                                 rep
ACCGACTTCATCGACGAGGAGGTGATCATGAGCATCGTGATCGAGAT... 1          1.274739
                                                   2          0.952963
                                                   3          0.967457
                                                   4               inf
ACCGACTTCATCGACGAGGAGGTGCTGATGAGCCTGGTGATCGAGAT... 1          0.535860
...                                                                ...
TTCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCAG... 4          0.645853
TTCGCCGACGCCACCCAGGCCGCCCTGCAGGCCGGCATTCCCTTCAG... 1          0.964500
                                                   2          0.748452
                                                   3          0.959533
                                                   4               inf

timepoint                                                               \
metric                                                 bc_activity_std
AD                                                 rep
ACCGACTTCATCGACGAGGAGGTGATCATGAGCATCGTGATCGAGAT... 1               NaN
                                                   2          0.066521
                                                   3          0.122369
                                                   4               NaN
ACCGACTTCATCGACGAGGAGGTGCTGATGAGCCTGGTGATCGAGAT... 1          0.430904
...                                                                ...
TTCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCAG... 4          0.086853
TTCGCCGACGCCACCCAGGCCGCCCTGCAGGCCGGCATTCCCTTCAG... 1          0.308504
                                                   2          0.289149
                                                   3          0.179148
                                                   4               NaN

timepoint                                                               \
metric                                                 pooled_activity
AD                                                 rep
ACCGACTTCATCGACGAGGAGGTGATCATGAGCATCGTGATCGAGAT... 1          1.274739
                                                   2          0.907132
                                                   3          0.928979
                                                   4          1.219512
ACCGACTTCATCGACGAGGAGGTGCTGATGAGCCTGGTGATCGAGAT... 1          0.504835
...                                                                ...
TTCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCAG... 4          0.636598
TTCGCCGACGCCACCCAGGCCGCCCTGCAGGCCGGCATTCCCTTCAG... 1          0.829122
                                                   2          0.704444
                                                   3          1.081372
                                                   4          4.039370

timepoint                                                           48  \
metric                                                 bc_activity_avg
AD                                                 rep
ACCGACTTCATCGACGAGGAGGTGATCATGAGCATCGTGATCGAGAT... 1          1.254359
                                                   2          7.421662
                                                   3          1.653242
                                                   4               inf
ACCGACTTCATCGACGAGGAGGTGCTGATGAGCCTGGTGATCGAGAT... 1          0.392915
...                                                                ...
TTCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCAG... 4          0.000966
TTCGCCGACGCCACCCAGGCCGCCCTGCAGGCCGGCATTCCCTTCAG... 1          1.110729
                                                   2          2.742500
                                                   3               inf
                                                   4               inf

timepoint                                                               \
metric                                                 bc_activity_std
AD                                                 rep
ACCGACTTCATCGACGAGGAGGTGATCATGAGCATCGTGATCGAGAT... 1               NaN
                                                   2          2.939214
                                                   3          0.762014
                                                   4               NaN
ACCGACTTCATCGACGAGGAGGTGCTGATGAGCCTGGTGATCGAGAT... 1          0.366932
...                                                                ...
TTCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCAG... 4          0.001673
TTCGCCGACGCCACCCAGGCCGCCCTGCAGGCCGGCATTCCCTTCAG... 1          0.366290
                                                   2          1.140543
                                                   3               NaN
                                                   4               NaN

timepoint                                                               \
metric                                                 pooled_activity
AD                                                 rep
ACCGACTTCATCGACGAGGAGGTGATCATGAGCATCGTGATCGAGAT... 1          1.254359
                                                   2          5.365854
                                                   3          1.854480
                                                   4          0.019608
ACCGACTTCATCGACGAGGAGGTGCTGATGAGCCTGGTGATCGAGAT... 1          0.383976
...                                                                ...
TTCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCAG... 4          0.000864
TTCGCCGACGCCACCCAGGCCGCCCTGCAGGCCGGCATTCCCTTCAG... 1          0.926357
                                                   2          2.451336
                                                   3          1.467576
                                                   4          0.010782

timepoint                                                            6  \
metric                                                 bc_activity_avg
AD                                                 rep
ACCGACTTCATCGACGAGGAGGTGATCATGAGCATCGTGATCGAGAT... 1          3.089943
                                                   2          1.246190
                                                   3          2.330575
                                                   4         13.501381
ACCGACTTCATCGACGAGGAGGTGCTGATGAGCCTGGTGATCGAGAT... 1          1.240475
...                                                                ...
TTCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCAG... 4               inf
TTCGCCGACGCCACCCAGGCCGCCCTGCAGGCCGGCATTCCCTTCAG... 1          2.164033
                                                   2          0.789712
                                                   3          2.693837
                                                   4               inf

timepoint                                                               \
metric                                                 bc_activity_std
AD                                                 rep
ACCGACTTCATCGACGAGGAGGTGATCATGAGCATCGTGATCGAGAT... 1               NaN
                                                   2          0.182165
                                                   3          0.200319
                                                   4         16.968609
ACCGACTTCATCGACGAGGAGGTGCTGATGAGCCTGGTGATCGAGAT... 1          0.993384
...                                                                ...
TTCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCAG... 4               NaN
TTCGCCGACGCCACCCAGGCCGCCCTGCAGGCCGGCATTCCCTTCAG... 1          0.322559
                                                   2          0.332761
                                                   3          0.550061
                                                   4               NaN

timepoint
metric                                                 pooled_activity
AD                                                 rep
ACCGACTTCATCGACGAGGAGGTGATCATGAGCATCGTGATCGAGAT... 1          3.089943
                                                   2          1.121076
                                                   3          2.275883
                                                   4          1.634615
ACCGACTTCATCGACGAGGAGGTGCTGATGAGCCTGGTGATCGAGAT... 1          1.144239
...                                                                ...
TTCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCAG... 4          1.032817
TTCGCCGACGCCACCCAGGCCGCCCTGCAGGCCGGCATTCCCTTCAG... 1          1.975227
                                                   2          0.844027
                                                   3          2.876429
                                                   4          8.137838

[832 rows x 18 columns]

In [9]:
# time_columns = [col for col in activity_mean_rim.columns if isinstance(col, int)]

# activity_mean_rim['na_count'] = activity_mean_rim.isna().sum(axis=1)

# # Filter rows with no nulls (na_count == 0) and no infinite values
# no_nulls_no_inf = activity_mean_rim[(activity_mean_rim['na_count'] == 0) &
#                                            (~activity_mean_rim[time_columns].isin([float('inf')]).any(axis=1))]

# # Filter rows with no nulls (na_count == 0) and select the first 10 rows
# no_nulls_no_inf_subset = no_nulls_no_inf.sample(10)

# # Select columns corresponding to time points (0-60)
# time_columns = [col for col in activity_mean_rim.columns if isinstance(col, int)]

# # Plot lineplot with 10 subplots
# fig, axes = plt.subplots(2,5, figsize=(12,6), sharex=True, sharey = True, dpi = 300)
# axes = axes.flatten()

# for i, (index, row) in enumerate(no_nulls_no_inf_subset.iterrows()):
#     ax = axes[i]
#     ax.plot(time_columns, row[time_columns], marker='o')
#     ax.set_yscale('log')

# fig.supylabel("Activity")
# fig.supxlabel("Time")

# plt.suptitle("NKX2-2 Activity: Puro Only, No Error Correction")
# sns.despine()
# plt.tight_layout()
# plt.show()

# 3. Puro only, err corr

In [10]:
pipeline_err_corr_puro_only = pipelines.TreblPipeline(
    db_path="",
    design_file_path="",
    error_correction=False,
    output_path="../../output/NKX2-2/TL4B2/puro_only/err_corr_100",
)

In [11]:
pipeline_err_corr_puro_only.calculate_activity_scores(
    step1_path="../../output/NKX2-2/pipeline_test/err_corr/step1.csv",
    AD_bc_objects=[trebl_exp_ADBC2, trebl_exp_HawkBCs],
    RT_bc_objects=[trebl_exp_RTBC],
    time_regex=r"_T(\d+)_",
    rep_regex=r"_R(\d+)_",
)

timepoint                                                            0  \
metric                                                 bc_activity_avg
AD                                                 rep
ACCGACGCCATCGACGAGGAGGTGGCCATGAGCGCCGTGATCGAGAT... 1               NaN
                                                   2               NaN
                                                   3               NaN
                                                   4               NaN
ACCGACTTCATCGACGAGGAGGTGATCATGAGCATCGTGATCGAGAT... 1               inf
...                                                                ...
TTCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCAG... 4               inf
TTCGCCGACGCCACCCAGGCCGCCCTGCAGGCCGGCATTCCCTTCAG... 1               inf
                                                   2               inf
                                                   3               inf
                                                   4               0.0

timepoint                                                               \
metric                                                 bc_activity_std
AD                                                 rep
ACCGACGCCATCGACGAGGAGGTGGCCATGAGCGCCGTGATCGAGAT... 1               NaN
                                                   2               NaN
                                                   3               NaN
                                                   4               NaN
ACCGACTTCATCGACGAGGAGGTGATCATGAGCATCGTGATCGAGAT... 1               NaN
...                                                                ...
TTCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCAG... 4               NaN
TTCGCCGACGCCACCCAGGCCGCCCTGCAGGCCGGCATTCCCTTCAG... 1               NaN
                                                   2               NaN
                                                   3               NaN
                                                   4               NaN

timepoint                                                               \
metric                                                 pooled_activity
AD                                                 rep
ACCGACGCCATCGACGAGGAGGTGGCCATGAGCGCCGTGATCGAGAT... 1               NaN
                                                   2               NaN
                                                   3               NaN
                                                   4               NaN
ACCGACTTCATCGACGAGGAGGTGATCATGAGCATCGTGATCGAGAT... 1          0.180556
...                                                                ...
TTCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCAG... 4          2.705882
TTCGCCGACGCCACCCAGGCCGCCCTGCAGGCCGGCATTCCCTTCAG... 1               inf
                                                   2          0.234259
                                                   3          7.611111
                                                   4          0.000000

timepoint                                                           24  \
metric                                                 bc_activity_avg
AD                                                 rep
ACCGACGCCATCGACGAGGAGGTGGCCATGAGCGCCGTGATCGAGAT... 1               inf
                                                   2          0.460526
                                                   3               NaN
                                                   4          0.000000
ACCGACTTCATCGACGAGGAGGTGATCATGAGCATCGTGATCGAGAT... 1          1.431957
...                                                                ...
TTCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCAG... 4               inf
TTCGCCGACGCCACCCAGGCCGCCCTGCAGGCCGGCATTCCCTTCAG... 1          1.239810
                                                   2               inf
                                                   3               inf
                                                   4               inf

timepoint                                                               \
metric                                                 bc_activity_std
AD                                                 rep
ACCGACGCCATCGACGAGGAGGTGGCCATGAGCGCCGTGATCGAGAT... 1               NaN
                                                   2               NaN
                                                   3               NaN
                                                   4               NaN
ACCGACTTCATCGACGAGGAGGTGATCATGAGCATCGTGATCGAGAT... 1               NaN
...                                                                ...
TTCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCAG... 4               NaN
TTCGCCGACGCCACCCAGGCCGCCCTGCAGGCCGGCATTCCCTTCAG... 1          0.366122
                                                   2               NaN
                                                   3               NaN
                                                   4               NaN

timepoint                                                               \
metric                                                 pooled_activity
AD                                                 rep
ACCGACGCCATCGACGAGGAGGTGGCCATGAGCGCCGTGATCGAGAT... 1               inf
                                                   2          0.460526
                                                   3               NaN
                                                   4          0.000000
ACCGACTTCATCGACGAGGAGGTGATCATGAGCATCGTGATCGAGAT... 1          1.431957
...                                                                ...
TTCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCAG... 4          0.862641
TTCGCCGACGCCACCCAGGCCGCCCTGCAGGCCGGCATTCCCTTCAG... 1          1.166309
                                                   2          1.620993
                                                   3          1.151529
                                                   4          1.367125

timepoint                                                            4  \
metric                                                 bc_activity_avg
AD                                                 rep
ACCGACGCCATCGACGAGGAGGTGGCCATGAGCGCCGTGATCGAGAT... 1               NaN
                                                   2          0.215686
                                                   3          0.000000
                                                   4               NaN
ACCGACTTCATCGACGAGGAGGTGATCATGAGCATCGTGATCGAGAT... 1          0.203936
...                                                                ...
TTCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCAG... 4               inf
TTCGCCGACGCCACCCAGGCCGCCCTGCAGGCCGGCATTCCCTTCAG... 1          0.266264
                                                   2               inf
                                                   3               inf
                                                   4               inf

timepoint                                                               \
metric                                                 bc_activity_std
AD                                                 rep
ACCGACGCCATCGACGAGGAGGTGGCCATGAGCGCCGTGATCGAGAT... 1               NaN
                                                   2               NaN
                                                   3               NaN
                                                   4               NaN
ACCGACTTCATCGACGAGGAGGTGATCATGAGCATCGTGATCGAGAT... 1          0.288408
...                                                                ...
TTCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCAG... 4               NaN
TTCGCCGACGCCACCCAGGCCGCCCTGCAGGCCGGCATTCCCTTCAG... 1          0.243877
                                                   2               NaN
                                                   3               NaN
                                                   4               NaN

timepoint                                                               \
metric                                                 pooled_activity
AD                                                 rep
ACCGACGCCATCGACGAGGAGGTGGCCATGAGCGCCGTGATCGAGAT... 1               NaN
                                                   2          0.215686
                                                   3          0.000000
                                                   4               NaN
ACCGACTTCATCGACGAGGAGGTGATCATGAGCATCGTGATCGAGAT... 1          0.364800
...                                                                ...
TTCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCAG... 4          0.527529
TTCGCCGACGCCACCCAGGCCGCCCTGCAGGCCGGCATTCCCTTCAG... 1          0.394180
                                                   2          0.428194
                                                   3          1.057778
                                                   4          0.457769

timepoint                                                           48  \
metric                                                 bc_activity_avg
AD                                                 rep
ACCGACGCCATCGACGAGGAGGTGGCCATGAGCGCCGTGATCGAGAT... 1               NaN
                                                   2          0.321534
                                                   3               NaN
                                                   4          0.000000
ACCGACTTCATCGACGAGGAGGTGATCATGAGCATCGTGATCGAGAT... 1               inf
...                                                                ...
TTCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCAG... 4          0.684827
TTCGCCGACGCCACCCAGGCCGCCCTGCAGGCCGGCATTCCCTTCAG... 1               inf
                                                   2               inf
                                                   3          0.493463
                                                   4               inf

timepoint                                                               \
metric                                                 bc_activity_std
AD                                                 rep
ACCGACGCCATCGACGAGGAGGTGGCCATGAGCGCCGTGATCGAGAT... 1               NaN
                                                   2               NaN
                                                   3               NaN
                                                   4               NaN
ACCGACTTCATCGACGAGGAGGTGATCATGAGCATCGTGATCGAGAT... 1               NaN
...                                                                ...
TTCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCAG... 4          0.786667
TTCGCCGACGCCACCCAGGCCGCCCTGCAGGCCGGCATTCCCTTCAG... 1               NaN
                                                   2               NaN
                                                   3          0.342662
                                                   4               NaN

timepoint
metric                                                 pooled_activity
AD                                                 rep
ACCGACGCCATCGACGAGGAGGTGGCCATGAGCGCCGTGATCGAGAT... 1               NaN
                                                   2          0.321534
                                                   3               NaN
                                                   4          0.000000
ACCGACTTCATCGACGAGGAGGTGATCATGAGCATCGTGATCGAGAT... 1               inf
...                                                                ...
TTCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCAG... 4          0.557848
TTCGCCGACGCCACCCAGGCCGCCCTGCAGGCCGGCATTCCCTTCAG... 1               inf
                                                   2          1.058717
                                                   3          0.574423
                                                   4          0.775871

[868 rows x 12 columns]

# 4. Rim, err corr

In [12]:
pipeline_err_corr_rim = pipelines.TreblPipeline(
    db_path="",
    design_file_path="",
    error_correction=False,
    output_path="../../output/NKX2-2/TL4B2/rim/err_corr_100",
)

In [13]:
pipeline_err_corr_rim.calculate_activity_scores(
    step1_path="../../output/NKX2-2/pipeline_test/err_corr/step1.csv",
    AD_bc_objects=[trebl_exp_ADBC2, trebl_exp_HawkBCs],
    RT_bc_objects=[trebl_exp_RTBC],
    time_regex=r"_T([^_]+)_",
    rep_regex=r"R(\d+)",
)

timepoint                                                            0  \
metric                                                 bc_activity_avg
AD                                                 rep
ACCGACTTCATCGACGAGGAGGTGATCATGAGCATCGTGATCGAGAT... 1          0.428026
                                                   2          0.514299
                                                   3          0.420903
                                                   4          0.544304
ACCGACTTCATCGACGAGGAGGTGCTGATGAGCCTGGTGATCGAGAT... 1          0.266006
...                                                                ...
TTCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCAG... 4          0.371471
TTCGCCGACGCCACCCAGGCCGCCCTGCAGGCCGGCATTCCCTTCAG... 1          0.443919
                                                   2               inf
                                                   3          0.691628
                                                   4               inf

timepoint                                                               \
metric                                                 bc_activity_std
AD                                                 rep
ACCGACTTCATCGACGAGGAGGTGATCATGAGCATCGTGATCGAGAT... 1               NaN
                                                   2          0.020222
                                                   3          0.043493
                                                   4               NaN
ACCGACTTCATCGACGAGGAGGTGCTGATGAGCCTGGTGATCGAGAT... 1          0.183206
...                                                                ...
TTCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCAG... 4          0.032353
TTCGCCGACGCCACCCAGGCCGCCCTGCAGGCCGGCATTCCCTTCAG... 1          0.120338
                                                   2               NaN
                                                   3          0.187103
                                                   4               NaN

timepoint                                                               \
metric                                                 pooled_activity
AD                                                 rep
ACCGACTTCATCGACGAGGAGGTGATCATGAGCATCGTGATCGAGAT... 1          0.428026
                                                   2          0.528105
                                                   3          0.432953
                                                   4          0.544304
ACCGACTTCATCGACGAGGAGGTGCTGATGAGCCTGGTGATCGAGAT... 1          0.270007
...                                                                ...
TTCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCAG... 4          0.363556
TTCGCCGACGCCACCCAGGCCGCCCTGCAGGCCGGCATTCCCTTCAG... 1          0.400560
                                                   2          0.476976
                                                   3          0.791401
                                                   4          2.834254

timepoint                                                          0ND  \
metric                                                 bc_activity_avg
AD                                                 rep
ACCGACTTCATCGACGAGGAGGTGATCATGAGCATCGTGATCGAGAT... 1          5.131019
                                                   2         10.287129
                                                   3          3.927244
                                                   4          9.000000
ACCGACTTCATCGACGAGGAGGTGCTGATGAGCCTGGTGATCGAGAT... 1          6.231026
...                                                                ...
TTCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCAG... 4         11.954327
TTCGCCGACGCCACCCAGGCCGCCCTGCAGGCCGGCATTCCCTTCAG... 1          8.130721
                                                   2               inf
                                                   3         12.424118
                                                   4               inf

timepoint                                                               \
metric                                                 bc_activity_std
AD                                                 rep
ACCGACTTCATCGACGAGGAGGTGATCATGAGCATCGTGATCGAGAT... 1               NaN
                                                   2               NaN
                                                   3          0.721611
                                                   4               NaN
ACCGACTTCATCGACGAGGAGGTGCTGATGAGCCTGGTGATCGAGAT... 1          4.628460
...                                                                ...
TTCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCAG... 4          4.395621
TTCGCCGACGCCACCCAGGCCGCCCTGCAGGCCGGCATTCCCTTCAG... 1          4.734103
                                                   2               NaN
                                                   3          7.654342
                                                   4               NaN

timepoint                                                               \
metric                                                 pooled_activity
AD                                                 rep
ACCGACTTCATCGACGAGGAGGTGATCATGAGCATCGTGATCGAGAT... 1          5.131019
                                                   2         10.287129
                                                   3          3.476364
                                                   4          9.000000
ACCGACTTCATCGACGAGGAGGTGCTGATGAGCCTGGTGATCGAGAT... 1          5.518113
...                                                                ...
TTCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCAG... 4         11.214286
TTCGCCGACGCCACCCAGGCCGCCCTGCAGGCCGGCATTCCCTTCAG... 1          8.792398
                                                   2          7.936759
                                                   3         16.442500
                                                   4         10.366071

timepoint                                                           24  \
metric                                                 bc_activity_avg
AD                                                 rep
ACCGACTTCATCGACGAGGAGGTGATCATGAGCATCGTGATCGAGAT... 1          1.829163
                                                   2          1.713640
                                                   3          1.931169
                                                   4               inf
ACCGACTTCATCGACGAGGAGGTGCTGATGAGCCTGGTGATCGAGAT... 1          0.746432
...                                                                ...
TTCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCAG... 4          0.862257
TTCGCCGACGCCACCCAGGCCGCCCTGCAGGCCGGCATTCCCTTCAG... 1          1.489702
                                                   2          1.132917
                                                   3          2.147267
                                                   4               inf

timepoint                                                               \
metric                                                 bc_activity_std
AD                                                 rep
ACCGACTTCATCGACGAGGAGGTGATCATGAGCATCGTGATCGAGAT... 1               NaN
                                                   2               NaN
                                                   3          0.102469
                                                   4               NaN
ACCGACTTCATCGACGAGGAGGTGCTGATGAGCCTGGTGATCGAGAT... 1          0.665269
...                                                                ...
TTCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCAG... 4          0.293372
TTCGCCGACGCCACCCAGGCCGCCCTGCAGGCCGGCATTCCCTTCAG... 1          0.239380
                                                   2          0.390100
                                                   3          0.384739
                                                   4               NaN

timepoint                                                               \
metric                                                 pooled_activity
AD                                                 rep
ACCGACTTCATCGACGAGGAGGTGATCATGAGCATCGTGATCGAGAT... 1          1.829163
                                                   2          1.713640
                                                   3          1.963351
                                                   4          1.468432
ACCGACTTCATCGACGAGGAGGTGCTGATGAGCCTGGTGATCGAGAT... 1          0.653828
...                                                                ...
TTCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCAG... 4          0.942085
TTCGCCGACGCCACCCAGGCCGCCCTGCAGGCCGGCATTCCCTTCAG... 1          1.416780
                                                   2          0.960522
                                                   3          2.285022
                                                   4          6.962704

timepoint                                                            4  \
metric                                                 bc_activity_avg
AD                                                 rep
ACCGACTTCATCGACGAGGAGGTGATCATGAGCATCGTGATCGAGAT... 1          1.278356
                                                   2          0.455065
                                                   3          0.967288
                                                   4               inf
ACCGACTTCATCGACGAGGAGGTGCTGATGAGCCTGGTGATCGAGAT... 1          0.536281
...                                                                ...
TTCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCAG... 4          0.648298
TTCGCCGACGCCACCCAGGCCGCCCTGCAGGCCGGCATTCCCTTCAG... 1          0.965522
                                                   2          0.754763
                                                   3          0.960305
                                                   4               inf

timepoint                                                               \
metric                                                 bc_activity_std
AD                                                 rep
ACCGACTTCATCGACGAGGAGGTGATCATGAGCATCGTGATCGAGAT... 1               NaN
                                                   2          0.643559
                                                   3          0.122412
                                                   4               NaN
ACCGACTTCATCGACGAGGAGGTGCTGATGAGCCTGGTGATCGAGAT... 1          0.431543
...                                                                ...
TTCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCAG... 4          0.091141
TTCGCCGACGCCACCCAGGCCGCCCTGCAGGCCGGCATTCCCTTCAG... 1          0.308155
                                                   2          0.310008
                                                   3          0.180072
                                                   4               NaN

timepoint                                                               \
metric                                                 pooled_activity
AD                                                 rep
ACCGACTTCATCGACGAGGAGGTGATCATGAGCATCGTGATCGAGAT... 1          1.278356
                                                   2          0.898462
                                                   3          0.928800
                                                   4          1.228311
ACCGACTTCATCGACGAGGAGGTGCTGATGAGCCTGGTGATCGAGAT... 1          0.505194
...                                                                ...
TTCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCAG... 4          0.638699
TTCGCCGACGCCACCCAGGCCGCCCTGCAGGCCGGCATTCCCTTCAG... 1          0.829939
                                                   2          0.666667
                                                   3          1.082193
                                                   4          4.026688

timepoint                                                           48  \
metric                                                 bc_activity_avg
AD                                                 rep
ACCGACTTCATCGACGAGGAGGTGATCATGAGCATCGTGATCGAGAT... 1          1.255885
                                                   2               inf
                                                   3          1.657935
                                                   4               inf
ACCGACTTCATCGACGAGGAGGTGCTGATGAGCCTGGTGATCGAGAT... 1          0.393386
...                                                                ...
TTCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCAG... 4          0.000000
TTCGCCGACGCCACCCAGGCCGCCCTGCAGGCCGGCATTCCCTTCAG... 1          1.114034
                                                   2               inf
                                                   3          1.394384
                                                   4          0.027027

timepoint                                                               \
metric                                                 bc_activity_std
AD                                                 rep
ACCGACTTCATCGACGAGGAGGTGATCATGAGCATCGTGATCGAGAT... 1               NaN
                                                   2               NaN
                                                   3          0.765416
                                                   4               NaN
ACCGACTTCATCGACGAGGAGGTGCTGATGAGCCTGGTGATCGAGAT... 1          0.367681
...                                                                ...
TTCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCAG... 4          0.000000
TTCGCCGACGCCACCCAGGCCGCCCTGCAGGCCGGCATTCCCTTCAG... 1          0.364067
                                                   2               NaN
                                                   3          0.225992
                                                   4          0.046812

timepoint                                                               \
metric                                                 pooled_activity
AD                                                 rep
ACCGACTTCATCGACGAGGAGGTGATCATGAGCATCGTGATCGAGAT... 1          1.255885
                                                   2          5.416894
                                                   3          1.860315
                                                   4          0.019553
ACCGACTTCATCGACGAGGAGGTGCTGATGAGCCTGGTGATCGAGAT... 1          0.384422
...                                                                ...
TTCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCAG... 4          0.000000
TTCGCCGACGCCACCCAGGCCGCCCTGCAGGCCGGCATTCCCTTCAG... 1          0.928325
                                                   2          2.387500
                                                   3          1.469685
                                                   4          0.008021

timepoint                                                            6  \
metric                                                 bc_activity_avg
AD                                                 rep
ACCGACTTCATCGACGAGGAGGTGATCATGAGCATCGTGATCGAGAT... 1          3.093949
                                                   2               inf
                                                   3          2.331826
                                                   4               inf
ACCGACTTCATCGACGAGGAGGTGCTGATGAGCCTGGTGATCGAGAT... 1          1.241837
...                                                                ...
TTCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCAG... 4          0.997700
TTCGCCGACGCCACCCAGGCCGCCCTGCAGGCCGGCATTCCCTTCAG... 1          2.162963
                                                   2          0.870312
                                                   3          2.695362
                                                   4               inf

timepoint                                                               \
metric                                                 bc_activity_std
AD                                                 rep
ACCGACTTCATCGACGAGGAGGTGATCATGAGCATCGTGATCGAGAT... 1               NaN
                                                   2               NaN
                                                   3          0.206969
                                                   4               NaN
ACCGACTTCATCGACGAGGAGGTGCTGATGAGCCTGGTGATCGAGAT... 1          0.995146
...                                                                ...
TTCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCAG... 4          0.161831
TTCGCCGACGCCACCCAGGCCGCCCTGCAGGCCGGCATTCCCTTCAG... 1          0.323168
                                                   2          0.055736
                                                   3          0.546324
                                                   4               NaN

timepoint
metric                                                 pooled_activity
AD                                                 rep
ACCGACTTCATCGACGAGGAGGTGATCATGAGCATCGTGATCGAGAT... 1          3.093949
                                                   2          1.138965
                                                   3          2.275046
                                                   4          1.649171
ACCGACTTCATCGACGAGGAGGTGCTGATGAGCCTGGTGATCGAGAT... 1          1.145425
...                                                                ...
TTCCAGGACCTGGCCGCCGCCACCTTCCAGGCCGGCATTCCCTTCAG... 4          1.038702
TTCGCCGACGCCACCCAGGCCGCCCTGCAGGCCGGCATTCCCTTCAG... 1          1.976799
                                                   2          0.803735
                                                   3          2.879137
                                                   4          8.715116

[770 rows x 18 columns]